name: Test-Build

on:
  push:
    branches:
      - main

jobs: 
  test-api:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Node.js
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Install dependencies
      - name: Install dependencies
        run: npm install

            # Start server
      - name: Start server
        run: npm run tern-on-api &

      # wait for server 
      - name: Wait for server to start
        run: |
          for i in {1..10}; do
            if nc -z localhost 3000; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server to start..."
            sleep 2
          done
          echo "Server failed to start" && exit 1

      # Install newman and reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      # Create directory for results
      - name: Make directory for results
        run: mkdir -p testResults

      # Run Postman collection
      - name: Run POSTMAN collection
        run: |
          newman run store.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
      # Шаг 9: Загружаем результаты тестов
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults